name: Deploy to GitHub Pages

on:
  push:
    branches: [main, dev, "feature/*"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

env:
  GITHUB_ROOT_PATH: /roadbook

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      # expose the full site prefix for the deploy job
      FULL_PAGE_PATH: ${{ steps.set-path.outputs.fullPath }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine branch sub‑folder
        id: set-path
        run: |
          BRANCH=${GITHUB_REF##*/}
          if [[ "$BRANCH" == "main" ]]; then
            SUFFIX=""
          else
            SUFFIX="/${BRANCH}"
          fi
          # fullPath is e.g. "/roadbook" or "/roadbook/dev" or "/roadbook/feature/foo"
          echo "fullPath=${GITHUB_ROOT_PATH}${SUFFIX}" >> $GITHUB_OUTPUT

      - name: Install & build with Astro
        env:
          PUBLIC_BASE_PATH: ${{ steps.set-path.outputs.fullPath }}
        uses: withastro/action@v3

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./dist
          destination_dir: .${{ needs.build.outputs.FULL_PAGE_PATH }}
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: christophschaller/christophschaller.github.io
          publish_branch: main
