name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - dev
      - 'feature/*'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Set base path environment variable
        run: |
          branch=${GITHUB_REF#refs/heads/}
          echo "Detected branch: $branch"
          if [ "$branch" = "main" ]; then
            echo "GITHUB_BASE_PATH=/roadbook" >> $GITHUB_ENV
          elif [ "$branch" = "dev" ]; then
            echo "GITHUB_BASE_PATH=/roadbook/dev" >> $GITHUB_ENV
          elif [[ "$branch" == feature/* ]]; then
            feature=${branch#feature/}
            echo "GITHUB_BASE_PATH=/roadbook/feature/$feature" >> $GITHUB_ENV
          fi

      - name: Install, build, and upload your site
        uses: withastro/action@v3
        env:
          GITHUB_BASE_PATH: ${{ env.GITHUB_BASE_PATH }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
